name: Finale

on: workflow_call

jobs:
  finale:
    runs-on: ubuntu-latest
    name: Final Jobs
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Download code coverage results
        uses: actions/download-artifact@v3
        with:
          name: coverage
          path: coverage

      - name: Display structure of downloaded files
        run: ls -R

      # - name: 📔 Generating coverage badges
      #   uses: jpb06/jest-badges-action@latest
      #   if: github.event_name != 'pull_request'
      #   with:
      #     branches: main,dev
      #     commit-message: 'chore: update coverage badges [skip ci]'
      #     output-folder: ./.github/badges
      #     coverage-summary-path: ./coverage/libs/browserslist-config/coverage-summary.json

      - name: 📋 TODO to Issue
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: alstr/todo-to-issue-action@v4
        with:
          AUTO_ASSIGN: true
