name: Merge

on:
  push:
    branches:
      - main
      - dev

jobs:
  ci-repo-integrity:
    name: Repo Integrity
    uses: ./.github/workflows/ci-repo-integrity.yml

  ci-nx:
    name: NX Commands
    needs: ci-repo-integrity
    uses: ./.github/workflows/ci-nx.yml

  ci-coverage-badge:
    name: Coverage Badge
    needs: ci-nx
    uses: ./.github/workflows/ci-coverage-badge.yml
    secrets: inherit

  ci-release:
    name: Release
    needs: ci-nx
    uses: ./.github/workflows/ci-release.yml
    secrets: inherit

  # https://stackoverflow.com/a/66358138
  ci-finale:
    name: Finale
    needs: [ci-coverage-badge, ci-release]
    if: |
      always()
      && contains(needs.*.result, 'success')
      && !contains(needs.*.result, 'failure')
    uses: ./.github/workflows/ci-finale.yml
