name: PR

on:
  pull_request:
    branches:
      - dev

jobs:
  ci-repo-integrity:
    name: Repo Integrity
    uses: ./.github/workflows/ci-repo-integrity.yml

  ci-nx:
    name: NX Commands
    needs: ci-repo-integrity
    uses: ./.github/workflows/ci-nx.yml

  # Consider removing cx-nx job if ci-coverage-badge calls it anyway
  ci-coverage-badge:
    name: Coverage Badge
    needs: ci-nx
    uses: ./.github/workflows/ci-coverage-badge.yml
